# Generated by Django 4.2.3 on 2023-08-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='password',
            field=models.CharField(default='Nilesh@123', max_length=30),
            preserve_default=False,
        ),
    ]
