# Generated by Django 4.2.3 on 2023-08-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0002_studentinfo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='image',
            field=models.ImageField(default=(255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255), upload_to=''),
            preserve_default=False,
        ),
    ]
